### ISSUE TITLE
The ensime repo doesn't have a master branch

### ISSUE THREAD

**Issue by hartzell** [sjrmanning/.emacs.d#1]
Straight complains when it tries to checkout the master branch of the *ensime-emacs* repository, which isn't surprising because it doesn't have one:

```
Warning (straight): Could not check out branch "master" of repository "ensime-emacs"
```

This change fixes it

```diff
diff --git a/modules/sm-coding-java.el b/modules/sm-coding-java.el
index fee6836..1f2e58f 100644
--- a/modules/sm-coding-java.el
+++ b/modules/sm-coding-java.el
@@ -1,6 +1,7 @@
 ;;; sm-coding-java.el --- Java and Android config.

 (use-package ensime
+  :straight (:repo "https://github.com/ensime/ensime-emacs" :branch "2.0")
   :commands java-mode)

 (use-package java
```

I would have preferred to be able to only specify the *branch*, and let the automagic bits whip up the other parts, but when I didn't specify a `:repo` I get a complaint as emacs starts up (trying to match a repo URL against `nil`, I think).

Perhaps @raxod502 knows a prettier way to do it.

ps.  **Thank you** for sharing your emacs config, it's been a great mind expander!

**Comment by raxod502** [comment]
1. Recipe inheritance would solve the problem about the verbosity, but this (greatly desired) feature is a while off: https://github.com/raxod502/straight.el/issues/116
2. I had previously assumed that MELPA used `master` by default. Instead, it appears that it uses the default branch of the repository if a custom `:branch` is not specified. This means that some MELPA recipes won't work with `straight.el`, which is a bug that should be fixed. Unfortunately, I can't think of a good way to achieve it at the moment: how would `straight.el` know which branch to check out when pulling the latest version? Let me know if you have thoughts: https://github.com/raxod502/straight.el/issues/279
3. I recommend `:host github :repo "ensime/ensime-emacs"`. It's more semantic :)

**Comment by sjrmanning** [comment]
Hey, thanks a lot for pointing this out, I completely missed this until now. I didn't know anyone was tracking this repo :) Really glad to hear it's been of some use! This should be fixed now.

**Comment by hartzell** [comment]
It's actually the most useful framework for an emacs config that I've seen.  Not too thin, not too big.  Just right....

Thanks for sharing!
